/*
Navicat SQL Server Data Transfer

Source Server         : hermes_pruebas
Source Server Version : 100000
Source Host           : 172.16.10.58:1433
Source Database       : kardex_medico
Source Schema         : dbo

Target Server Type    : SQL Server
Target Server Version : 100000
File Encoding         : 65001

Date: 2018-09-07 08:45:25
*/


-- ----------------------------
-- Table structure for [dbo].[ADM_CATEGORIA]
-- ----------------------------
DROP TABLE [dbo].[ADM_CATEGORIA]
GO
CREATE TABLE [dbo].[ADM_CATEGORIA] (
[ID_ADM_CATEGORIA] int NOT NULL IDENTITY(1,1) ,
[ID_MENU] int NULL ,
[DESCRIPCION] varchar(50) NULL ,
[ABREVIACION] varchar(10) NULL ,
[RUTA_ENLACE] varchar(50) NULL ,
[ORDEN] int NULL ,
[ESTADO] int NOT NULL 
)


GO

-- ----------------------------
-- Records of ADM_CATEGORIA
-- ----------------------------
SET IDENTITY_INSERT [dbo].[ADM_CATEGORIA] ON
GO
SET IDENTITY_INSERT [dbo].[ADM_CATEGORIA] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[ADM_MENU]
-- ----------------------------
DROP TABLE [dbo].[ADM_MENU]
GO
CREATE TABLE [dbo].[ADM_MENU] (
[ID_MENU] int NOT NULL IDENTITY(1,1) ,
[DESCRIPCION] varchar(50) NULL ,
[ABREVIACION] varchar(10) NULL ,
[RUTA_ENLACE] varchar(30) NULL ,
[ORDEN] int NULL ,
[ESTADO] int NOT NULL 
)


GO

-- ----------------------------
-- Records of ADM_MENU
-- ----------------------------
SET IDENTITY_INSERT [dbo].[ADM_MENU] ON
GO
SET IDENTITY_INSERT [dbo].[ADM_MENU] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[ADM_ROL]
-- ----------------------------
DROP TABLE [dbo].[ADM_ROL]
GO
CREATE TABLE [dbo].[ADM_ROL] (
[ID_ROL] int NOT NULL IDENTITY(1,1) ,
[DESCRIPCION] varchar(30) NULL ,
[ABREVIACION] varchar(10) NULL ,
[ESTADO] int NOT NULL 
)


GO

-- ----------------------------
-- Records of ADM_ROL
-- ----------------------------
SET IDENTITY_INSERT [dbo].[ADM_ROL] ON
GO
SET IDENTITY_INSERT [dbo].[ADM_ROL] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[ADM_ROL_MENU]
-- ----------------------------
DROP TABLE [dbo].[ADM_ROL_MENU]
GO
CREATE TABLE [dbo].[ADM_ROL_MENU] (
[ID_ADM_ROL_MENU] int NOT NULL IDENTITY(1,1) ,
[ID_ROL] int NULL ,
[ID_MENU] int NULL ,
[ESTADO] int NOT NULL 
)


GO

-- ----------------------------
-- Records of ADM_ROL_MENU
-- ----------------------------
SET IDENTITY_INSERT [dbo].[ADM_ROL_MENU] ON
GO
SET IDENTITY_INSERT [dbo].[ADM_ROL_MENU] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[ADM_USUARIO]
-- ----------------------------
DROP TABLE [dbo].[ADM_USUARIO]
GO
CREATE TABLE [dbo].[ADM_USUARIO] (
[ID_USUARIO] int NOT NULL IDENTITY(1,1) ,
[ID_PERSONA] int NOT NULL ,
[NOMBRE_USUARIO] varchar(15) NOT NULL ,
[CONTRASENIA] varchar(200) NOT NULL ,
[DIRECCION] varchar(50) NULL ,
[CELULAR] varchar(12) NULL ,
[TELEFONO] varchar(12) NULL ,
[GENERO] int NULL ,
[CORREO_ELECTRONICO] varchar(30) NULL ,
[FECHA_NACIMIENTO] datetime NULL ,
[FECHA_REGISTRO] datetime NOT NULL ,
[FECHA_MODIFICACION] datetime NULL ,
[USUARIO_REGISTRO] int NOT NULL ,
[USUARIO_MODIFICACION] int NULL ,
[ESTADO] int NOT NULL ,
[ACTIVO] bit NULL ,
[ROL] int NULL DEFAULT ((1)) 
)


GO
DBCC CHECKIDENT(N'[dbo].[ADM_USUARIO]', RESEED, 7)
GO

-- ----------------------------
-- Records of ADM_USUARIO
-- ----------------------------
SET IDENTITY_INSERT [dbo].[ADM_USUARIO] ON
GO
INSERT INTO [dbo].[ADM_USUARIO] ([ID_USUARIO], [ID_PERSONA], [NOMBRE_USUARIO], [CONTRASENIA], [DIRECCION], [CELULAR], [TELEFONO], [GENERO], [CORREO_ELECTRONICO], [FECHA_NACIMIENTO], [FECHA_REGISTRO], [FECHA_MODIFICACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [ESTADO], [ACTIVO], [ROL]) VALUES (N'1', N'1', N'agduran', N'123456', N'Montes', N'70682025', N'22280656', N'1', N'01agduran@gmail.com', N'1900-01-01 00:00:00.000', N'2018-08-08 12:44:10.700', N'2018-08-08 12:44:10.700', N'1', N'1', N'1', N'1', N'1');
GO
INSERT INTO [dbo].[ADM_USUARIO] ([ID_USUARIO], [ID_PERSONA], [NOMBRE_USUARIO], [CONTRASENIA], [DIRECCION], [CELULAR], [TELEFONO], [GENERO], [CORREO_ELECTRONICO], [FECHA_NACIMIENTO], [FECHA_REGISTRO], [FECHA_MODIFICACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [ESTADO], [ACTIVO], [ROL]) VALUES (N'2', N'2', N'hmontes', N'$2a$10$cw50Z1a.R5RsOV5upyRrB.Q4eN/7oSxIPytxEUWLo6eXN/QuX2Rv.', N'S/D', N'S/D', N'N/S', N'1', N'hmontes@cofar.com.bo', N'1992-02-12 00:00:00.000', N'2018-08-08 12:44:10.700', N'2018-08-08 12:44:10.700', N'2', N'2', N'1', N'1', N'1');
GO
INSERT INTO [dbo].[ADM_USUARIO] ([ID_USUARIO], [ID_PERSONA], [NOMBRE_USUARIO], [CONTRASENIA], [DIRECCION], [CELULAR], [TELEFONO], [GENERO], [CORREO_ELECTRONICO], [FECHA_NACIMIENTO], [FECHA_REGISTRO], [FECHA_MODIFICACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [ESTADO], [ACTIVO], [ROL]) VALUES (N'3', N'3', N'agduran2', N'123456', N'Montes', N'70682025', N'22280656', N'1', N'01agduran@gmail.com', N'1992-02-12 00:00:00.000', N'2018-08-08 12:44:10.700', N'2018-08-08 12:44:10.700', N'3', N'3', N'1', N'1', N'1');
GO
INSERT INTO [dbo].[ADM_USUARIO] ([ID_USUARIO], [ID_PERSONA], [NOMBRE_USUARIO], [CONTRASENIA], [DIRECCION], [CELULAR], [TELEFONO], [GENERO], [CORREO_ELECTRONICO], [FECHA_NACIMIENTO], [FECHA_REGISTRO], [FECHA_MODIFICACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [ESTADO], [ACTIVO], [ROL]) VALUES (N'4', N'4', N'agduran3', N'123456', N'Montes', N'70682025', N'22280656', N'1', N'01agduran@gmail.com', N'1992-02-12 00:00:00.000', N'2018-08-08 12:44:10.700', N'2018-08-08 12:44:10.700', N'1', N'1', N'1', N'1', N'1');
GO
INSERT INTO [dbo].[ADM_USUARIO] ([ID_USUARIO], [ID_PERSONA], [NOMBRE_USUARIO], [CONTRASENIA], [DIRECCION], [CELULAR], [TELEFONO], [GENERO], [CORREO_ELECTRONICO], [FECHA_NACIMIENTO], [FECHA_REGISTRO], [FECHA_MODIFICACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [ESTADO], [ACTIVO], [ROL]) VALUES (N'5', N'5', N'agduran4', N'123456', N'Montes', N'70682025', N'22280656', N'1', N'01agduran@gmail.com', N'1992-02-12 00:00:00.000', N'2018-08-08 12:44:10.700', N'2018-08-08 12:44:10.700', N'2', N'2', N'1', N'1', N'1');
GO
INSERT INTO [dbo].[ADM_USUARIO] ([ID_USUARIO], [ID_PERSONA], [NOMBRE_USUARIO], [CONTRASENIA], [DIRECCION], [CELULAR], [TELEFONO], [GENERO], [CORREO_ELECTRONICO], [FECHA_NACIMIENTO], [FECHA_REGISTRO], [FECHA_MODIFICACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [ESTADO], [ACTIVO], [ROL]) VALUES (N'6', N'5', N'admin', N'$2a$10$cw50Z1a.R5RsOV5upyRrB.Q4eN/7oSxIPytxEUWLo6eXN/QuX2Rv.', N'Montes', N'70682025', N'22280656', N'1', N'01agduran@gmail.com', N'1992-12-02 00:00:00.000', N'2018-08-08 12:44:10.700', N'2018-08-08 12:44:10.700', N'2', N'2', N'1', N'1', N'1');
GO
INSERT INTO [dbo].[ADM_USUARIO] ([ID_USUARIO], [ID_PERSONA], [NOMBRE_USUARIO], [CONTRASENIA], [DIRECCION], [CELULAR], [TELEFONO], [GENERO], [CORREO_ELECTRONICO], [FECHA_NACIMIENTO], [FECHA_REGISTRO], [FECHA_MODIFICACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [ESTADO], [ACTIVO], [ROL]) VALUES (N'7', N'5', N'squispe', N'$2a$10$cw50Z1a.R5RsOV5upyRrB.Q4eN/7oSxIPytxEUWLo6eXN/QuX2Rv.', N'Montes', N'70682025', N'22280656', N'1', N'01agduran@gmail.com', N'1992-12-02 00:00:00.000', N'2018-08-08 12:44:10.700', N'2018-08-08 12:44:10.700', N'2', N'2', N'1', N'1', N'1');
GO
SET IDENTITY_INSERT [dbo].[ADM_USUARIO] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[ADM_USUARIO_ROL]
-- ----------------------------
DROP TABLE [dbo].[ADM_USUARIO_ROL]
GO
CREATE TABLE [dbo].[ADM_USUARIO_ROL] (
[ID_ADM_USUARIO_ROL] int NOT NULL IDENTITY(1,1) ,
[ID_USUARIO] int NULL ,
[ID_ROL] int NULL ,
[FECHA_REGISTRO] datetime NOT NULL ,
[FECHA_MODIFICACION] datetime NULL ,
[FECHA_EXPIRACION] datetime NULL ,
[ESTADO] int NOT NULL 
)


GO

-- ----------------------------
-- Records of ADM_USUARIO_ROL
-- ----------------------------
SET IDENTITY_INSERT [dbo].[ADM_USUARIO_ROL] ON
GO
SET IDENTITY_INSERT [dbo].[ADM_USUARIO_ROL] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[HER_DIRECCION]
-- ----------------------------
DROP TABLE [dbo].[HER_DIRECCION]
GO
CREATE TABLE [dbo].[HER_DIRECCION] (
[ID_DIRECCION] int NOT NULL IDENTITY(1,1) ,
[DIRECCION] varchar(60) NULL ,
[NRO_DIRECCION] varchar(5) NULL ,
[TELEFONO] varchar(10) NULL ,
[EMAIL] varchar(60) NULL ,
[AVENIDA_CALLE] varchar(60) NULL ,
[USUARIO_REGISTRO] int NOT NULL ,
[USUARIO_MODIFICACION] int NULL ,
[FECHA_REGISTRO] datetime NOT NULL ,
[FECHA_MODIFICACION] datetime NULL ,
[ESTADO] int NOT NULL DEFAULT ((0)) 
)


GO

-- ----------------------------
-- Records of HER_DIRECCION
-- ----------------------------
SET IDENTITY_INSERT [dbo].[HER_DIRECCION] ON
GO
SET IDENTITY_INSERT [dbo].[HER_DIRECCION] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[HER_ESPECIALIDAD]
-- ----------------------------
DROP TABLE [dbo].[HER_ESPECIALIDAD]
GO
CREATE TABLE [dbo].[HER_ESPECIALIDAD] (
[ID_ESPECIALIDAD] int NOT NULL IDENTITY(1,1) ,
[DESCRIPCION] varchar(150) NULL ,
[ABREVIACION] varchar(10) NULL ,
[USUARIO_REGISTRO] int NOT NULL ,
[USUARIO_MODIFICACION] int NULL ,
[FECHA_REGISTRO] datetime NOT NULL ,
[FECHA_MODIFICACION] datetime NULL ,
[ESTADO] int NOT NULL 
)


GO
DBCC CHECKIDENT(N'[dbo].[HER_ESPECIALIDAD]', RESEED, 9)
GO

-- ----------------------------
-- Records of HER_ESPECIALIDAD
-- ----------------------------
SET IDENTITY_INSERT [dbo].[HER_ESPECIALIDAD] ON
GO
INSERT INTO [dbo].[HER_ESPECIALIDAD] ([ID_ESPECIALIDAD], [DESCRIPCION], [ABREVIACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'1', N'MED. GENERAL', N'MED-GEN', N'1', null, N'2018-09-06 21:57:37.220', null, N'1');
GO
INSERT INTO [dbo].[HER_ESPECIALIDAD] ([ID_ESPECIALIDAD], [DESCRIPCION], [ABREVIACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'2', N'GINECOLOGÍA', N'GIN', N'1', null, N'2018-09-06 21:57:37.220', null, N'1');
GO
INSERT INTO [dbo].[HER_ESPECIALIDAD] ([ID_ESPECIALIDAD], [DESCRIPCION], [ABREVIACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'3', N'ODONTOLOGÍA', N'ODO', N'1', null, N'2018-09-06 21:57:37.220', null, N'1');
GO
INSERT INTO [dbo].[HER_ESPECIALIDAD] ([ID_ESPECIALIDAD], [DESCRIPCION], [ABREVIACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'4', N'OFTALMOLOGIA', N'OFT', N'1', null, N'2018-09-06 21:57:37.220', null, N'1');
GO
INSERT INTO [dbo].[HER_ESPECIALIDAD] ([ID_ESPECIALIDAD], [DESCRIPCION], [ABREVIACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'5', N'MED.INTERNA', N'MED-INT', N'1', null, N'2018-09-06 21:57:37.220', null, N'1');
GO
INSERT INTO [dbo].[HER_ESPECIALIDAD] ([ID_ESPECIALIDAD], [DESCRIPCION], [ABREVIACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'6', N'OTORRINOLARINGOLOGIA', N'OTO', N'1', null, N'2018-09-06 21:57:37.220', null, N'1');
GO
INSERT INTO [dbo].[HER_ESPECIALIDAD] ([ID_ESPECIALIDAD], [DESCRIPCION], [ABREVIACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'7', N'REUMATOLOGIA', N'REU', N'1', null, N'2018-09-06 21:57:37.220', null, N'1');
GO
INSERT INTO [dbo].[HER_ESPECIALIDAD] ([ID_ESPECIALIDAD], [DESCRIPCION], [ABREVIACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'8', N'x', N'X', N'1', null, N'2018-09-06 21:57:37.220', null, N'1');
GO
INSERT INTO [dbo].[HER_ESPECIALIDAD] ([ID_ESPECIALIDAD], [DESCRIPCION], [ABREVIACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'9', N'x', N'X', N'1', null, N'2018-09-06 21:57:37.220', null, N'1');
GO
SET IDENTITY_INSERT [dbo].[HER_ESPECIALIDAD] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[HER_ESTADO_CIVIL]
-- ----------------------------
DROP TABLE [dbo].[HER_ESTADO_CIVIL]
GO
CREATE TABLE [dbo].[HER_ESTADO_CIVIL] (
[ID_ESTADO_CIVIL] int NOT NULL IDENTITY(1,1) ,
[DESCRIPCION] varchar(150) NULL ,
[ABREVIACION] varchar(12) NULL ,
[USUARIO_REGISTRO] int NOT NULL ,
[USUARIO_MODIFICACION] int NULL ,
[FECHA_REGISTRO] datetime NOT NULL ,
[FECHA_MODIFICACION] datetime NULL ,
[ESTADO] int NOT NULL 
)


GO
DBCC CHECKIDENT(N'[dbo].[HER_ESTADO_CIVIL]', RESEED, 4)
GO

-- ----------------------------
-- Records of HER_ESTADO_CIVIL
-- ----------------------------
SET IDENTITY_INSERT [dbo].[HER_ESTADO_CIVIL] ON
GO
INSERT INTO [dbo].[HER_ESTADO_CIVIL] ([ID_ESTADO_CIVIL], [DESCRIPCION], [ABREVIACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'1', N'Soltero(a)', N'SOLT', N'1', N'1', N'2018-09-06 11:40:24.733', null, N'1');
GO
INSERT INTO [dbo].[HER_ESTADO_CIVIL] ([ID_ESTADO_CIVIL], [DESCRIPCION], [ABREVIACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'2', N'Viudo(a) Mod', N'AA MOd', N'1', N'1', N'2018-09-06 11:40:24.733', N'2018-09-06 11:40:24.733', N'1');
GO
INSERT INTO [dbo].[HER_ESTADO_CIVIL] ([ID_ESTADO_CIVIL], [DESCRIPCION], [ABREVIACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'3', N'Divorciado(a)', N'DIV', N'1', N'1', N'2018-09-06 11:40:24.733', null, N'1');
GO
INSERT INTO [dbo].[HER_ESTADO_CIVIL] ([ID_ESTADO_CIVIL], [DESCRIPCION], [ABREVIACION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'4', N'Viudo(a) Mod', N'SOLT', N'1', N'1', N'2018-09-06 11:40:24.737', N'2018-09-06 11:40:24.737', N'0');
GO
SET IDENTITY_INSERT [dbo].[HER_ESTADO_CIVIL] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[HER_FARMACIA_REF_MEDICO]
-- ----------------------------
DROP TABLE [dbo].[HER_FARMACIA_REF_MEDICO]
GO
CREATE TABLE [dbo].[HER_FARMACIA_REF_MEDICO] (
[ID_FARMACIA_REF_MEDICO] int NOT NULL IDENTITY(1,1) ,
[ID_MEDICO] int NULL ,
[ID_FARMACIA_REFERENCIA] int NULL ,
[ESTADO] int NOT NULL 
)


GO

-- ----------------------------
-- Records of HER_FARMACIA_REF_MEDICO
-- ----------------------------
SET IDENTITY_INSERT [dbo].[HER_FARMACIA_REF_MEDICO] ON
GO
SET IDENTITY_INSERT [dbo].[HER_FARMACIA_REF_MEDICO] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[HER_FARMACIA_REFERENCIA]
-- ----------------------------
DROP TABLE [dbo].[HER_FARMACIA_REFERENCIA]
GO
CREATE TABLE [dbo].[HER_FARMACIA_REFERENCIA] (
[ID_FARMACIA_REFERENCIA] int NOT NULL IDENTITY(1,1) ,
[NOMBRE_FARMACIA] varchar(50) NULL ,
[DIRECCION_FARMACIA] varchar(60) NULL ,
[USUARIO_REGISTRO] int NOT NULL ,
[USUARIO_MODIFICACION] int NULL ,
[FECHA_REGISTRO] datetime NOT NULL ,
[FECHA_MODIFICACION] datetime NULL ,
[ESTADO] int NOT NULL 
)


GO

-- ----------------------------
-- Records of HER_FARMACIA_REFERENCIA
-- ----------------------------
SET IDENTITY_INSERT [dbo].[HER_FARMACIA_REFERENCIA] ON
GO
SET IDENTITY_INSERT [dbo].[HER_FARMACIA_REFERENCIA] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[HER_HORARIO_TRABAJO]
-- ----------------------------
DROP TABLE [dbo].[HER_HORARIO_TRABAJO]
GO
CREATE TABLE [dbo].[HER_HORARIO_TRABAJO] (
[ID_HORARIO_TRABAJO] int NOT NULL IDENTITY(1,1) ,
[ID_LUGAR_TRABAJO] int NULL ,
[ID_TURNO] int NULL ,
[LUNES] bit NULL DEFAULT ((0)) ,
[MARTES] bit NULL DEFAULT ((0)) ,
[MIERCOLES] bit NULL DEFAULT ((0)) ,
[JUEVES] bit NULL DEFAULT ((0)) ,
[VIERNES] bit NULL DEFAULT ((0)) ,
[USUARIO_REGISTRO] int NULL ,
[USUARIO_MODIFICACION] int NULL ,
[FECHA_REGISTRO] datetime NULL ,
[FECHA_MODIFICACION] datetime NULL ,
[ESTADO] int NULL 
)


GO

-- ----------------------------
-- Records of HER_HORARIO_TRABAJO
-- ----------------------------
SET IDENTITY_INSERT [dbo].[HER_HORARIO_TRABAJO] ON
GO
SET IDENTITY_INSERT [dbo].[HER_HORARIO_TRABAJO] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[HER_LINEA]
-- ----------------------------
DROP TABLE [dbo].[HER_LINEA]
GO
CREATE TABLE [dbo].[HER_LINEA] (
[ID_LINEA] int NOT NULL IDENTITY(1,1) ,
[DESCRIPCION] varchar(150) NULL ,
[USUARIO_REGISTRO] int NOT NULL ,
[USUARIO_MODIFICACION] int NULL ,
[FECHA_REGISTRO] datetime NOT NULL ,
[FECHA_MODIFICACION] datetime NULL ,
[ESTADO] int NOT NULL ,
[ABREVIACION] varchar(20) NULL 
)


GO
DBCC CHECKIDENT(N'[dbo].[HER_LINEA]', RESEED, 9)
GO

-- ----------------------------
-- Records of HER_LINEA
-- ----------------------------
SET IDENTITY_INSERT [dbo].[HER_LINEA] ON
GO
INSERT INTO [dbo].[HER_LINEA] ([ID_LINEA], [DESCRIPCION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO], [ABREVIACION]) VALUES (N'1', N'DOLOR NEURO', N'1', N'1', N'2018-09-06 21:57:34.457', N'2018-09-06 21:57:37.220', N'1', null);
GO
INSERT INTO [dbo].[HER_LINEA] ([ID_LINEA], [DESCRIPCION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO], [ABREVIACION]) VALUES (N'2', N'ANTIBIOTICOS', N'1', N'1', N'2018-09-06 21:57:34.457', N'2018-09-06 21:57:37.220', N'1', null);
GO
INSERT INTO [dbo].[HER_LINEA] ([ID_LINEA], [DESCRIPCION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO], [ABREVIACION]) VALUES (N'3', N'OSTEOARTICULAR', N'1', N'1', N'2018-09-06 21:57:34.457', N'2018-09-06 21:57:37.220', N'1', null);
GO
INSERT INTO [dbo].[HER_LINEA] ([ID_LINEA], [DESCRIPCION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO], [ABREVIACION]) VALUES (N'4', N'CARDIO', N'1', N'1', N'2018-09-06 21:57:34.457', N'2018-09-06 21:57:37.220', N'1', null);
GO
INSERT INTO [dbo].[HER_LINEA] ([ID_LINEA], [DESCRIPCION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO], [ABREVIACION]) VALUES (N'5', N'VIDILINE', N'1', N'1', N'2018-09-06 21:57:34.457', N'2018-09-06 21:57:37.220', N'1', null);
GO
INSERT INTO [dbo].[HER_LINEA] ([ID_LINEA], [DESCRIPCION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO], [ABREVIACION]) VALUES (N'6', N'GASTRO', N'1', N'1', N'2018-09-06 21:57:34.457', N'2018-09-06 21:57:37.220', N'1', null);
GO
INSERT INTO [dbo].[HER_LINEA] ([ID_LINEA], [DESCRIPCION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO], [ABREVIACION]) VALUES (N'7', N'OSTEOARTICULAR', N'1', N'1', N'2018-09-06 21:57:34.457', N'2018-09-06 21:57:37.220', N'1', null);
GO
INSERT INTO [dbo].[HER_LINEA] ([ID_LINEA], [DESCRIPCION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO], [ABREVIACION]) VALUES (N'8', N'FLEXICAM', N'1', N'1', N'2018-09-06 21:57:34.457', N'2018-09-06 21:57:37.220', N'1', null);
GO
INSERT INTO [dbo].[HER_LINEA] ([ID_LINEA], [DESCRIPCION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO], [ABREVIACION]) VALUES (N'9', N'PEDIATRICA', N'1', N'1', N'2018-09-06 21:57:34.457', N'2018-09-06 21:57:37.220', N'1', null);
GO
SET IDENTITY_INSERT [dbo].[HER_LINEA] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[HER_LINEA_ESPECIALIDAD]
-- ----------------------------
DROP TABLE [dbo].[HER_LINEA_ESPECIALIDAD]
GO
CREATE TABLE [dbo].[HER_LINEA_ESPECIALIDAD] (
[ID_LINEA_ESPECIALIDAD] int NOT NULL IDENTITY(1,1) ,
[ID_LINEA] int NULL ,
[ID_ESPECIALIDAD] int NULL ,
[ESTADO] int NOT NULL 
)


GO

-- ----------------------------
-- Records of HER_LINEA_ESPECIALIDAD
-- ----------------------------
SET IDENTITY_INSERT [dbo].[HER_LINEA_ESPECIALIDAD] ON
GO
SET IDENTITY_INSERT [dbo].[HER_LINEA_ESPECIALIDAD] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[HER_LUGAR_TRABAJO]
-- ----------------------------
DROP TABLE [dbo].[HER_LUGAR_TRABAJO]
GO
CREATE TABLE [dbo].[HER_LUGAR_TRABAJO] (
[ID_LUGAR_TRABAJO] int NOT NULL IDENTITY(1,1) ,
[ID_SECRETARIA] int NULL ,
[ID_DIRECCION] int NULL ,
[ID_MEDICO] int NULL ,
[DESCRIPCION] varchar(150) NULL ,
[NRO_PACIENTES] int NULL ,
[COSTO_CONSULTA] float(53) NULL ,
[LONGITUD] varchar(150) NULL ,
[LATITUD] varchar(150) NULL ,
[CARGO] varchar(50) NULL ,
[USUARIO_REGISTRO] int NOT NULL ,
[USUARIO_MODIFICACION] int NULL ,
[FECHA_REGISTRO] datetime NOT NULL ,
[FECHA_MODIFICACION] datetime NULL ,
[ESTADO] int NULL 
)


GO

-- ----------------------------
-- Records of HER_LUGAR_TRABAJO
-- ----------------------------
SET IDENTITY_INSERT [dbo].[HER_LUGAR_TRABAJO] ON
GO
SET IDENTITY_INSERT [dbo].[HER_LUGAR_TRABAJO] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[HER_MED_ESPE]
-- ----------------------------
DROP TABLE [dbo].[HER_MED_ESPE]
GO
CREATE TABLE [dbo].[HER_MED_ESPE] (
[ID_MED_ESPE] int NOT NULL IDENTITY(1,1) ,
[ID_MEDICO] int NOT NULL ,
[ID_ESPECIALIDAD] int NULL ,
[FECHA_OBTENCION_ESPECIALIDAD] datetime NULL ,
[LUGAR_OBTENCION_ESPECIALIDAD] varchar(100) NULL ,
[USUARIO_REGISTRO] int NOT NULL ,
[USUARIO_MODIFICACION] int NULL ,
[FECHA_REGISTRO] datetime NOT NULL ,
[FECHA_MODIFICACION] datetime NULL ,
[ESTADO] int NOT NULL 
)


GO
DBCC CHECKIDENT(N'[dbo].[HER_MED_ESPE]', RESEED, 4)
GO

-- ----------------------------
-- Records of HER_MED_ESPE
-- ----------------------------
SET IDENTITY_INSERT [dbo].[HER_MED_ESPE] ON
GO
INSERT INTO [dbo].[HER_MED_ESPE] ([ID_MED_ESPE], [ID_MEDICO], [ID_ESPECIALIDAD], [FECHA_OBTENCION_ESPECIALIDAD], [LUGAR_OBTENCION_ESPECIALIDAD], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'1', N'4', N'1', N'2000-09-07 12:35:30.367', N'BOLIVIA', N'1', N'1', N'2018-09-07 12:35:46.713', N'2018-09-07 12:35:51.330', N'1');
GO
INSERT INTO [dbo].[HER_MED_ESPE] ([ID_MED_ESPE], [ID_MEDICO], [ID_ESPECIALIDAD], [FECHA_OBTENCION_ESPECIALIDAD], [LUGAR_OBTENCION_ESPECIALIDAD], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'2', N'4', N'2', N'2000-09-07 12:35:30.367', N'ECUADOR', N'1', N'1', N'2018-09-07 12:35:46.713', N'2018-09-07 12:35:51.330', N'1');
GO
INSERT INTO [dbo].[HER_MED_ESPE] ([ID_MED_ESPE], [ID_MEDICO], [ID_ESPECIALIDAD], [FECHA_OBTENCION_ESPECIALIDAD], [LUGAR_OBTENCION_ESPECIALIDAD], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'3', N'5', N'7', N'2000-09-07 12:35:30.367', N'ARGENTINA', N'1', N'1', N'2018-09-07 12:35:46.713', N'2018-09-07 12:35:51.330', N'1');
GO
INSERT INTO [dbo].[HER_MED_ESPE] ([ID_MED_ESPE], [ID_MEDICO], [ID_ESPECIALIDAD], [FECHA_OBTENCION_ESPECIALIDAD], [LUGAR_OBTENCION_ESPECIALIDAD], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'4', N'5', N'8', N'2000-09-07 12:35:30.367', N'ESPAÑA', N'1', N'1', N'2018-09-07 12:35:46.713', N'2018-09-07 12:35:51.330', N'1');
GO
SET IDENTITY_INSERT [dbo].[HER_MED_ESPE] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[HER_MEDICO]
-- ----------------------------
DROP TABLE [dbo].[HER_MEDICO]
GO
CREATE TABLE [dbo].[HER_MEDICO] (
[ID_MEDICO] int NOT NULL IDENTITY(1,1) ,
[ID_PERFIL_PROFESIONAL] int NULL ,
[ID_PERFIL_PSICOGRAFICO] int NULL ,
[ID_PERFIL_PERSONAL] int NULL ,
[ID_ESTADO_CIVIL] int NOT NULL ,
[ID_REGIONAL] int NULL ,
[AP_PATERNO] varchar(30) NULL ,
[AP_MATERNO] varchar(30) NULL ,
[NOMBRES] varchar(50) NOT NULL ,
[FECHA_NACIMIENTO] datetime NULL ,
[TELEFONO] varchar(10) NULL ,
[CELULAR] varchar(10) NULL ,
[CORREO_ELECTRONICO] varchar(25) NULL ,
[GENERO] int NOT NULL ,
[USUARIO_REGISTRO] int NOT NULL ,
[USUARIO_MODIFICACION] int NULL ,
[FECHA_REGISTRO] datetime NOT NULL ,
[FECHA_MODIFICACION] datetime NULL ,
[ESTADO] int NOT NULL 
)


GO
DBCC CHECKIDENT(N'[dbo].[HER_MEDICO]', RESEED, 9)
GO

-- ----------------------------
-- Records of HER_MEDICO
-- ----------------------------
SET IDENTITY_INSERT [dbo].[HER_MEDICO] ON
GO
INSERT INTO [dbo].[HER_MEDICO] ([ID_MEDICO], [ID_PERFIL_PROFESIONAL], [ID_PERFIL_PSICOGRAFICO], [ID_PERFIL_PERSONAL], [ID_ESTADO_CIVIL], [ID_REGIONAL], [AP_PATERNO], [AP_MATERNO], [NOMBRES], [FECHA_NACIMIENTO], [TELEFONO], [CELULAR], [CORREO_ELECTRONICO], [GENERO], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'4', N'1', N'1', N'2', N'1', N'1', N'Perez', N'Mamani', N'Mario Paolo', N'1975-09-06 22:57:55.147', N'222222', N'706522522', N'aa1@gmail.com', N'1', N'1', N'1', N'2018-09-06 22:58:24.197', N'2018-09-06 22:58:27.820', N'1');
GO
INSERT INTO [dbo].[HER_MEDICO] ([ID_MEDICO], [ID_PERFIL_PROFESIONAL], [ID_PERFIL_PSICOGRAFICO], [ID_PERFIL_PERSONAL], [ID_ESTADO_CIVIL], [ID_REGIONAL], [AP_PATERNO], [AP_MATERNO], [NOMBRES], [FECHA_NACIMIENTO], [TELEFONO], [CELULAR], [CORREO_ELECTRONICO], [GENERO], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'5', N'1', N'1', N'2', N'1', N'1', N'Cuenca', N'Perez', N'Mario Antonio', N'1975-09-06 22:57:55.147', N'225555', N'706522523', N'aa2@gmail.com', N'1', N'1', N'1', N'2018-09-06 22:58:24.197', N'2018-09-06 22:58:27.820', N'1');
GO
INSERT INTO [dbo].[HER_MEDICO] ([ID_MEDICO], [ID_PERFIL_PROFESIONAL], [ID_PERFIL_PSICOGRAFICO], [ID_PERFIL_PERSONAL], [ID_ESTADO_CIVIL], [ID_REGIONAL], [AP_PATERNO], [AP_MATERNO], [NOMBRES], [FECHA_NACIMIENTO], [TELEFONO], [CELULAR], [CORREO_ELECTRONICO], [GENERO], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'6', N'1', N'1', N'2', N'1', N'1', N'Camacho', N'Mendoza', N'Carlos Manuela', N'1975-09-06 22:57:55.147', N'222223', N'706522524', N'aa3@gmail.com', N'1', N'1', N'1', N'2018-09-06 22:58:24.197', N'2018-09-06 22:58:27.820', N'1');
GO
INSERT INTO [dbo].[HER_MEDICO] ([ID_MEDICO], [ID_PERFIL_PROFESIONAL], [ID_PERFIL_PSICOGRAFICO], [ID_PERFIL_PERSONAL], [ID_ESTADO_CIVIL], [ID_REGIONAL], [AP_PATERNO], [AP_MATERNO], [NOMBRES], [FECHA_NACIMIENTO], [TELEFONO], [CELULAR], [CORREO_ELECTRONICO], [GENERO], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'7', N'1', N'1', N'2', N'1', N'1', N'Tapia', N'Mallea', N'Julia Martina', N'1975-09-06 22:57:55.147', N'222224', N'706522525', N'aa4@gmail.com', N'1', N'1', N'1', N'2018-09-06 22:58:24.197', N'2018-09-06 22:58:27.820', N'1');
GO
INSERT INTO [dbo].[HER_MEDICO] ([ID_MEDICO], [ID_PERFIL_PROFESIONAL], [ID_PERFIL_PSICOGRAFICO], [ID_PERFIL_PERSONAL], [ID_ESTADO_CIVIL], [ID_REGIONAL], [AP_PATERNO], [AP_MATERNO], [NOMBRES], [FECHA_NACIMIENTO], [TELEFONO], [CELULAR], [CORREO_ELECTRONICO], [GENERO], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'8', N'1', N'1', N'2', N'1', N'1', N'Peralta', N'Cabrera', N'Nuevo Ingresado , hace un momento', N'1975-09-06 22:57:55.147', N'222225', N'706522526', N'aa5@gmail.com', N'1', N'1', N'1', N'2018-09-06 22:58:24.197', N'2018-09-06 22:58:27.820', N'1');
GO
INSERT INTO [dbo].[HER_MEDICO] ([ID_MEDICO], [ID_PERFIL_PROFESIONAL], [ID_PERFIL_PSICOGRAFICO], [ID_PERFIL_PERSONAL], [ID_ESTADO_CIVIL], [ID_REGIONAL], [AP_PATERNO], [AP_MATERNO], [NOMBRES], [FECHA_NACIMIENTO], [TELEFONO], [CELULAR], [CORREO_ELECTRONICO], [GENERO], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'9', N'1', N'1', N'2', N'1', N'1', N'Perez', N'Mamani', N'Mario Paolo', N'1975-09-06 22:57:55.147', N'222226', N'706522527', N'aa6@gmail.com', N'1', N'1', N'1', N'2018-09-06 22:58:24.197', N'2018-09-06 22:58:27.820', N'1');
GO
SET IDENTITY_INSERT [dbo].[HER_MEDICO] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[HER_PERFIL_PERSONAL]
-- ----------------------------
DROP TABLE [dbo].[HER_PERFIL_PERSONAL]
GO
CREATE TABLE [dbo].[HER_PERFIL_PERSONAL] (
[ID_PERFIL_PERSONAL] int NOT NULL IDENTITY(1,1) ,
[NOMBRE_CONYUGUE] varchar(60) NULL ,
[NOMBRE_HIJOS_EDAD] varchar(150) NULL ,
[ORIGEN_FAMILIA] varchar(50) NULL ,
[GRUPOS_SOCIALES] varchar(100) NULL ,
[AMIGOS] varchar(100) NULL ,
[COMIDA_PREFERIDA] varchar(50) NULL ,
[BEBIDA_PREFERIDA] varchar(50) NULL ,
[MASCOTA] varchar(50) NULL ,
[TIPO_MUSICA_PREFERIDA] varchar(50) NULL ,
[INSTRUMENTO_PREFERIDO] varchar(50) NULL ,
[GUSTOS_GENERALES] varchar(150) NULL ,
[HOBBIES] varchar(70) NULL ,
[USUARIO_REGISTRO] int NOT NULL ,
[USUARIO_MODIFICACION] int NULL ,
[FECHA_REGISTRO] datetime NOT NULL ,
[FECHA_MODIFICACION] datetime NULL ,
[ESTADO] int NOT NULL 
)


GO
DBCC CHECKIDENT(N'[dbo].[HER_PERFIL_PERSONAL]', RESEED, 2)
GO

-- ----------------------------
-- Records of HER_PERFIL_PERSONAL
-- ----------------------------
SET IDENTITY_INSERT [dbo].[HER_PERFIL_PERSONAL] ON
GO
INSERT INTO [dbo].[HER_PERFIL_PERSONAL] ([ID_PERFIL_PERSONAL], [NOMBRE_CONYUGUE], [NOMBRE_HIJOS_EDAD], [ORIGEN_FAMILIA], [GRUPOS_SOCIALES], [AMIGOS], [COMIDA_PREFERIDA], [BEBIDA_PREFERIDA], [MASCOTA], [TIPO_MUSICA_PREFERIDA], [INSTRUMENTO_PREFERIDO], [GUSTOS_GENERALES], [HOBBIES], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'2', N'Maria', N'Martin 4', N'Boliviana', N'Club tenis', N'Pedro,Julio,Mario', N'Fricase', N'Cerveza', N'PERRO', N'JAZZ', N'SAXO', N'DORMIR', N'VER PELICULAS', N'1', null, N'2018-09-06 18:51:33.530', null, N'1');
GO
SET IDENTITY_INSERT [dbo].[HER_PERFIL_PERSONAL] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[HER_PERFIL_PROFESIONAL]
-- ----------------------------
DROP TABLE [dbo].[HER_PERFIL_PROFESIONAL]
GO
CREATE TABLE [dbo].[HER_PERFIL_PROFESIONAL] (
[ID_PERFIL_PROFESIONAL] int NOT NULL IDENTITY(1,1) ,
[INSTITUCION] varchar(150) NULL ,
[COLEGAS] varchar(150) NULL ,
[USUARIO_REGISTRO] int NOT NULL ,
[USUARIO_MODIFICACION] int NULL ,
[FECHA_REGISTRO] datetime NOT NULL ,
[FECHA_MODIFICACION] datetime NULL ,
[ESTADO] int NULL 
)


GO
DBCC CHECKIDENT(N'[dbo].[HER_PERFIL_PROFESIONAL]', RESEED, 2)
GO

-- ----------------------------
-- Records of HER_PERFIL_PROFESIONAL
-- ----------------------------
SET IDENTITY_INSERT [dbo].[HER_PERFIL_PROFESIONAL] ON
GO
INSERT INTO [dbo].[HER_PERFIL_PROFESIONAL] ([ID_PERFIL_PROFESIONAL], [INSTITUCION], [COLEGAS], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'1', N'UMSA', N'Juan pary,', N'1', N'1', N'2018-09-06 18:51:13.223', N'2018-09-06 18:51:13.223', N'1');
GO
INSERT INTO [dbo].[HER_PERFIL_PROFESIONAL] ([ID_PERFIL_PROFESIONAL], [INSTITUCION], [COLEGAS], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'2', N'UMSA', N'Juan pary,', N'1', N'1', N'2018-09-06 18:51:33.530', N'2018-09-06 18:51:33.530', N'1');
GO
SET IDENTITY_INSERT [dbo].[HER_PERFIL_PROFESIONAL] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[HER_PERFIL_PSICOGRAFICO]
-- ----------------------------
DROP TABLE [dbo].[HER_PERFIL_PSICOGRAFICO]
GO
CREATE TABLE [dbo].[HER_PERFIL_PSICOGRAFICO] (
[ID_PERFIL_PSICOGRAFICO] int NOT NULL IDENTITY(1,1) ,
[DESCRIPCION] varchar(150) NULL ,
[USUARIO_REGISTRO] int NOT NULL ,
[USUARIO_MODIFICACION] int NULL ,
[FECHA_REGISTRO] datetime NOT NULL ,
[FECHA_MODIFICACION] datetime NULL ,
[ESTADO] int NOT NULL 
)


GO
DBCC CHECKIDENT(N'[dbo].[HER_PERFIL_PSICOGRAFICO]', RESEED, 2)
GO

-- ----------------------------
-- Records of HER_PERFIL_PSICOGRAFICO
-- ----------------------------
SET IDENTITY_INSERT [dbo].[HER_PERFIL_PSICOGRAFICO] ON
GO
INSERT INTO [dbo].[HER_PERFIL_PSICOGRAFICO] ([ID_PERFIL_PSICOGRAFICO], [DESCRIPCION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'1', N'HDP', N'1', N'1', N'2018-09-06 18:51:13.227', N'2018-09-06 18:51:13.227', N'1');
GO
INSERT INTO [dbo].[HER_PERFIL_PSICOGRAFICO] ([ID_PERFIL_PSICOGRAFICO], [DESCRIPCION], [USUARIO_REGISTRO], [USUARIO_MODIFICACION], [FECHA_REGISTRO], [FECHA_MODIFICACION], [ESTADO]) VALUES (N'2', N'HDP', N'1', N'1', N'2018-09-06 18:51:33.530', N'2018-09-06 18:51:33.530', N'1');
GO
SET IDENTITY_INSERT [dbo].[HER_PERFIL_PSICOGRAFICO] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[HER_PRODUCTO]
-- ----------------------------
DROP TABLE [dbo].[HER_PRODUCTO]
GO
CREATE TABLE [dbo].[HER_PRODUCTO] (
[ID_PRODUCTO] int NOT NULL IDENTITY(1,1) ,
[ID_LINEA] int NULL ,
[DESCRIPCION] varchar(150) NULL ,
[CANTIDAD] int NULL ,
[USUARIO_REGISTRO] int NULL ,
[USUARIO_MODIFICACION] int NULL ,
[FECHA_REGISTRO] datetime NULL ,
[FECHA_MODIFICACION] datetime NULL ,
[ESTADO] int NULL 
)


GO

-- ----------------------------
-- Records of HER_PRODUCTO
-- ----------------------------
SET IDENTITY_INSERT [dbo].[HER_PRODUCTO] ON
GO
SET IDENTITY_INSERT [dbo].[HER_PRODUCTO] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[HER_SECRETARIA]
-- ----------------------------
DROP TABLE [dbo].[HER_SECRETARIA]
GO
CREATE TABLE [dbo].[HER_SECRETARIA] (
[ID_SECRETARIA] int NOT NULL IDENTITY(1,1) ,
[ID_LUGAR_TRABAJO] int NULL ,
[AP_PATERNO] varchar(30) NULL ,
[AP_MATERNO] varchar(30) NULL ,
[NOMBRES] varchar(50) NULL ,
[FECHA_NACIMIENTO] datetime NULL ,
[TELEFONO] varchar(10) NULL ,
[CELULAR] varchar(10) NULL ,
[CORREO_ELECTRONICO] varchar(25) NULL ,
[GENERO] int NULL ,
[USUARIO_REGISTRO] int NOT NULL ,
[USUARIO_MODIFICACION] int NULL ,
[FECHA_REGISTRO] datetime NOT NULL ,
[FECHA_MODIFICACION] datetime NULL ,
[ESTADO] int NOT NULL 
)


GO

-- ----------------------------
-- Records of HER_SECRETARIA
-- ----------------------------
SET IDENTITY_INSERT [dbo].[HER_SECRETARIA] ON
GO
SET IDENTITY_INSERT [dbo].[HER_SECRETARIA] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[HER_TURNO]
-- ----------------------------
DROP TABLE [dbo].[HER_TURNO]
GO
CREATE TABLE [dbo].[HER_TURNO] (
[ID_TURNO] int NOT NULL IDENTITY(1,1) ,
[DESCRIPCION] varchar(150) NOT NULL ,
[HORA_ATENCION_INICIO] datetime NULL ,
[HORA_ATENCION_FIN] datetime NULL ,
[ESTADO] int NULL 
)


GO

-- ----------------------------
-- Records of HER_TURNO
-- ----------------------------
SET IDENTITY_INSERT [dbo].[HER_TURNO] ON
GO
SET IDENTITY_INSERT [dbo].[HER_TURNO] OFF
GO

-- ----------------------------
-- Table structure for [dbo].[REGIONAL]
-- ----------------------------
DROP TABLE [dbo].[REGIONAL]
GO
CREATE TABLE [dbo].[REGIONAL] (
[ID_REGIONAL] int NOT NULL IDENTITY(1,1) ,
[DESCRIPCION] varchar(150) NULL ,
[ESTADO] int NULL 
)


GO

-- ----------------------------
-- Records of REGIONAL
-- ----------------------------
SET IDENTITY_INSERT [dbo].[REGIONAL] ON
GO
INSERT INTO [dbo].[REGIONAL] ([ID_REGIONAL], [DESCRIPCION], [ESTADO]) VALUES (N'1', N'La Paz', N'1');
GO
SET IDENTITY_INSERT [dbo].[REGIONAL] OFF
GO

-- ----------------------------
-- Indexes structure for table ADM_CATEGORIA
-- ----------------------------
CREATE INDEX [FK_22_FK] ON [dbo].[ADM_CATEGORIA]
([ID_MENU] ASC) 
GO

-- ----------------------------
-- Primary Key structure for table [dbo].[ADM_CATEGORIA]
-- ----------------------------
ALTER TABLE [dbo].[ADM_CATEGORIA] ADD PRIMARY KEY ([ID_ADM_CATEGORIA])
GO

-- ----------------------------
-- Indexes structure for table ADM_MENU
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table [dbo].[ADM_MENU]
-- ----------------------------
ALTER TABLE [dbo].[ADM_MENU] ADD PRIMARY KEY ([ID_MENU])
GO

-- ----------------------------
-- Indexes structure for table ADM_ROL
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table [dbo].[ADM_ROL]
-- ----------------------------
ALTER TABLE [dbo].[ADM_ROL] ADD PRIMARY KEY ([ID_ROL])
GO

-- ----------------------------
-- Indexes structure for table ADM_ROL_MENU
-- ----------------------------
CREATE INDEX [FK_20_FK] ON [dbo].[ADM_ROL_MENU]
([ID_ROL] ASC) 
GO
CREATE INDEX [FK_21_FK] ON [dbo].[ADM_ROL_MENU]
([ID_MENU] ASC) 
GO

-- ----------------------------
-- Primary Key structure for table [dbo].[ADM_ROL_MENU]
-- ----------------------------
ALTER TABLE [dbo].[ADM_ROL_MENU] ADD PRIMARY KEY ([ID_ADM_ROL_MENU])
GO

-- ----------------------------
-- Indexes structure for table ADM_USUARIO
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table [dbo].[ADM_USUARIO]
-- ----------------------------
ALTER TABLE [dbo].[ADM_USUARIO] ADD PRIMARY KEY ([ID_USUARIO])
GO

-- ----------------------------
-- Indexes structure for table ADM_USUARIO_ROL
-- ----------------------------
CREATE INDEX [FK_18_FK] ON [dbo].[ADM_USUARIO_ROL]
([ID_USUARIO] ASC) 
GO
CREATE INDEX [FK_19_FK] ON [dbo].[ADM_USUARIO_ROL]
([ID_ROL] ASC) 
GO

-- ----------------------------
-- Primary Key structure for table [dbo].[ADM_USUARIO_ROL]
-- ----------------------------
ALTER TABLE [dbo].[ADM_USUARIO_ROL] ADD PRIMARY KEY ([ID_ADM_USUARIO_ROL])
GO

-- ----------------------------
-- Indexes structure for table HER_DIRECCION
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table [dbo].[HER_DIRECCION]
-- ----------------------------
ALTER TABLE [dbo].[HER_DIRECCION] ADD PRIMARY KEY ([ID_DIRECCION])
GO

-- ----------------------------
-- Indexes structure for table HER_ESPECIALIDAD
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table [dbo].[HER_ESPECIALIDAD]
-- ----------------------------
ALTER TABLE [dbo].[HER_ESPECIALIDAD] ADD PRIMARY KEY ([ID_ESPECIALIDAD])
GO

-- ----------------------------
-- Indexes structure for table HER_ESTADO_CIVIL
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table [dbo].[HER_ESTADO_CIVIL]
-- ----------------------------
ALTER TABLE [dbo].[HER_ESTADO_CIVIL] ADD PRIMARY KEY ([ID_ESTADO_CIVIL])
GO

-- ----------------------------
-- Indexes structure for table HER_FARMACIA_REF_MEDICO
-- ----------------------------
CREATE INDEX [FK_1_FK] ON [dbo].[HER_FARMACIA_REF_MEDICO]
([ID_MEDICO] ASC) 
GO
CREATE INDEX [FK_5_FK] ON [dbo].[HER_FARMACIA_REF_MEDICO]
([ID_FARMACIA_REFERENCIA] ASC) 
GO

-- ----------------------------
-- Primary Key structure for table [dbo].[HER_FARMACIA_REF_MEDICO]
-- ----------------------------
ALTER TABLE [dbo].[HER_FARMACIA_REF_MEDICO] ADD PRIMARY KEY ([ID_FARMACIA_REF_MEDICO])
GO

-- ----------------------------
-- Indexes structure for table HER_FARMACIA_REFERENCIA
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table [dbo].[HER_FARMACIA_REFERENCIA]
-- ----------------------------
ALTER TABLE [dbo].[HER_FARMACIA_REFERENCIA] ADD PRIMARY KEY ([ID_FARMACIA_REFERENCIA])
GO

-- ----------------------------
-- Indexes structure for table HER_HORARIO_TRABAJO
-- ----------------------------
CREATE INDEX [FK_14_FK] ON [dbo].[HER_HORARIO_TRABAJO]
([ID_LUGAR_TRABAJO] ASC) 
GO
CREATE INDEX [FK_16_FK] ON [dbo].[HER_HORARIO_TRABAJO]
([ID_TURNO] ASC) 
GO

-- ----------------------------
-- Primary Key structure for table [dbo].[HER_HORARIO_TRABAJO]
-- ----------------------------
ALTER TABLE [dbo].[HER_HORARIO_TRABAJO] ADD PRIMARY KEY ([ID_HORARIO_TRABAJO])
GO

-- ----------------------------
-- Indexes structure for table HER_LINEA
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table [dbo].[HER_LINEA]
-- ----------------------------
ALTER TABLE [dbo].[HER_LINEA] ADD PRIMARY KEY ([ID_LINEA])
GO

-- ----------------------------
-- Indexes structure for table HER_LINEA_ESPECIALIDAD
-- ----------------------------
CREATE INDEX [FK_11_FK] ON [dbo].[HER_LINEA_ESPECIALIDAD]
([ID_LINEA] ASC) 
GO
CREATE INDEX [RELATIONSHIP_23_FK] ON [dbo].[HER_LINEA_ESPECIALIDAD]
([ID_ESPECIALIDAD] ASC) 
GO

-- ----------------------------
-- Primary Key structure for table [dbo].[HER_LINEA_ESPECIALIDAD]
-- ----------------------------
ALTER TABLE [dbo].[HER_LINEA_ESPECIALIDAD] ADD PRIMARY KEY ([ID_LINEA_ESPECIALIDAD])
GO

-- ----------------------------
-- Indexes structure for table HER_LUGAR_TRABAJO
-- ----------------------------
CREATE INDEX [FK_4_FK] ON [dbo].[HER_LUGAR_TRABAJO]
([ID_MEDICO] ASC) 
GO
CREATE INDEX [FK_15_FK] ON [dbo].[HER_LUGAR_TRABAJO]
([ID_DIRECCION] ASC) 
GO

-- ----------------------------
-- Primary Key structure for table [dbo].[HER_LUGAR_TRABAJO]
-- ----------------------------
ALTER TABLE [dbo].[HER_LUGAR_TRABAJO] ADD PRIMARY KEY ([ID_LUGAR_TRABAJO])
GO

-- ----------------------------
-- Indexes structure for table HER_MED_ESPE
-- ----------------------------
CREATE INDEX [FK_8_FK] ON [dbo].[HER_MED_ESPE]
([ID_MEDICO] ASC) 
GO
CREATE INDEX [RELATIONSHIP_22_FK] ON [dbo].[HER_MED_ESPE]
([ID_ESPECIALIDAD] ASC) 
GO

-- ----------------------------
-- Primary Key structure for table [dbo].[HER_MED_ESPE]
-- ----------------------------
ALTER TABLE [dbo].[HER_MED_ESPE] ADD PRIMARY KEY ([ID_MED_ESPE])
GO

-- ----------------------------
-- Indexes structure for table HER_MEDICO
-- ----------------------------
CREATE INDEX [FK_2_FK] ON [dbo].[HER_MEDICO]
([ID_ESTADO_CIVIL] ASC) 
GO
CREATE INDEX [FK_6_FK] ON [dbo].[HER_MEDICO]
([ID_PERFIL_PROFESIONAL] ASC) 
GO
CREATE INDEX [FK_7_FK] ON [dbo].[HER_MEDICO]
([ID_PERFIL_PSICOGRAFICO] ASC) 
GO
CREATE INDEX [FK_9_FK] ON [dbo].[HER_MEDICO]
([ID_PERFIL_PERSONAL] ASC) 
GO
CREATE INDEX [FK_3_FK] ON [dbo].[HER_MEDICO]
([ID_REGIONAL] ASC) 
GO

-- ----------------------------
-- Primary Key structure for table [dbo].[HER_MEDICO]
-- ----------------------------
ALTER TABLE [dbo].[HER_MEDICO] ADD PRIMARY KEY ([ID_MEDICO])
GO

-- ----------------------------
-- Indexes structure for table HER_PERFIL_PERSONAL
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table [dbo].[HER_PERFIL_PERSONAL]
-- ----------------------------
ALTER TABLE [dbo].[HER_PERFIL_PERSONAL] ADD PRIMARY KEY ([ID_PERFIL_PERSONAL])
GO

-- ----------------------------
-- Indexes structure for table HER_PERFIL_PROFESIONAL
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table [dbo].[HER_PERFIL_PROFESIONAL]
-- ----------------------------
ALTER TABLE [dbo].[HER_PERFIL_PROFESIONAL] ADD PRIMARY KEY ([ID_PERFIL_PROFESIONAL])
GO

-- ----------------------------
-- Indexes structure for table HER_PERFIL_PSICOGRAFICO
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table [dbo].[HER_PERFIL_PSICOGRAFICO]
-- ----------------------------
ALTER TABLE [dbo].[HER_PERFIL_PSICOGRAFICO] ADD PRIMARY KEY ([ID_PERFIL_PSICOGRAFICO])
GO

-- ----------------------------
-- Indexes structure for table HER_PRODUCTO
-- ----------------------------
CREATE INDEX [FK_12_FK] ON [dbo].[HER_PRODUCTO]
([ID_LINEA] ASC) 
GO

-- ----------------------------
-- Primary Key structure for table [dbo].[HER_PRODUCTO]
-- ----------------------------
ALTER TABLE [dbo].[HER_PRODUCTO] ADD PRIMARY KEY ([ID_PRODUCTO])
GO

-- ----------------------------
-- Indexes structure for table HER_SECRETARIA
-- ----------------------------
CREATE INDEX [RELATIONSHIP_21_FK] ON [dbo].[HER_SECRETARIA]
([ID_LUGAR_TRABAJO] ASC) 
GO

-- ----------------------------
-- Primary Key structure for table [dbo].[HER_SECRETARIA]
-- ----------------------------
ALTER TABLE [dbo].[HER_SECRETARIA] ADD PRIMARY KEY ([ID_SECRETARIA])
GO

-- ----------------------------
-- Indexes structure for table HER_TURNO
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table [dbo].[HER_TURNO]
-- ----------------------------
ALTER TABLE [dbo].[HER_TURNO] ADD PRIMARY KEY ([ID_TURNO])
GO

-- ----------------------------
-- Indexes structure for table REGIONAL
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table [dbo].[REGIONAL]
-- ----------------------------
ALTER TABLE [dbo].[REGIONAL] ADD PRIMARY KEY ([ID_REGIONAL])
GO

-- ----------------------------
-- Foreign Key structure for table [dbo].[ADM_CATEGORIA]
-- ----------------------------
ALTER TABLE [dbo].[ADM_CATEGORIA] ADD FOREIGN KEY ([ID_MENU]) REFERENCES [dbo].[ADM_MENU] ([ID_MENU]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

-- ----------------------------
-- Foreign Key structure for table [dbo].[ADM_ROL_MENU]
-- ----------------------------
ALTER TABLE [dbo].[ADM_ROL_MENU] ADD FOREIGN KEY ([ID_ROL]) REFERENCES [dbo].[ADM_ROL] ([ID_ROL]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [dbo].[ADM_ROL_MENU] ADD FOREIGN KEY ([ID_MENU]) REFERENCES [dbo].[ADM_MENU] ([ID_MENU]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

-- ----------------------------
-- Foreign Key structure for table [dbo].[ADM_USUARIO_ROL]
-- ----------------------------
ALTER TABLE [dbo].[ADM_USUARIO_ROL] ADD FOREIGN KEY ([ID_USUARIO]) REFERENCES [dbo].[ADM_USUARIO] ([ID_USUARIO]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [dbo].[ADM_USUARIO_ROL] ADD FOREIGN KEY ([ID_ROL]) REFERENCES [dbo].[ADM_ROL] ([ID_ROL]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

-- ----------------------------
-- Foreign Key structure for table [dbo].[HER_FARMACIA_REF_MEDICO]
-- ----------------------------
ALTER TABLE [dbo].[HER_FARMACIA_REF_MEDICO] ADD FOREIGN KEY ([ID_MEDICO]) REFERENCES [dbo].[HER_MEDICO] ([ID_MEDICO]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [dbo].[HER_FARMACIA_REF_MEDICO] ADD FOREIGN KEY ([ID_FARMACIA_REFERENCIA]) REFERENCES [dbo].[HER_FARMACIA_REFERENCIA] ([ID_FARMACIA_REFERENCIA]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

-- ----------------------------
-- Foreign Key structure for table [dbo].[HER_HORARIO_TRABAJO]
-- ----------------------------
ALTER TABLE [dbo].[HER_HORARIO_TRABAJO] ADD FOREIGN KEY ([ID_LUGAR_TRABAJO]) REFERENCES [dbo].[HER_LUGAR_TRABAJO] ([ID_LUGAR_TRABAJO]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [dbo].[HER_HORARIO_TRABAJO] ADD FOREIGN KEY ([ID_TURNO]) REFERENCES [dbo].[HER_TURNO] ([ID_TURNO]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

-- ----------------------------
-- Foreign Key structure for table [dbo].[HER_LINEA_ESPECIALIDAD]
-- ----------------------------
ALTER TABLE [dbo].[HER_LINEA_ESPECIALIDAD] ADD FOREIGN KEY ([ID_LINEA]) REFERENCES [dbo].[HER_LINEA] ([ID_LINEA]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [dbo].[HER_LINEA_ESPECIALIDAD] ADD FOREIGN KEY ([ID_ESPECIALIDAD]) REFERENCES [dbo].[HER_ESPECIALIDAD] ([ID_ESPECIALIDAD]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

-- ----------------------------
-- Foreign Key structure for table [dbo].[HER_LUGAR_TRABAJO]
-- ----------------------------
ALTER TABLE [dbo].[HER_LUGAR_TRABAJO] ADD FOREIGN KEY ([ID_DIRECCION]) REFERENCES [dbo].[HER_DIRECCION] ([ID_DIRECCION]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [dbo].[HER_LUGAR_TRABAJO] ADD FOREIGN KEY ([ID_MEDICO]) REFERENCES [dbo].[HER_MEDICO] ([ID_MEDICO]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

-- ----------------------------
-- Foreign Key structure for table [dbo].[HER_MED_ESPE]
-- ----------------------------
ALTER TABLE [dbo].[HER_MED_ESPE] ADD FOREIGN KEY ([ID_MEDICO]) REFERENCES [dbo].[HER_MEDICO] ([ID_MEDICO]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [dbo].[HER_MED_ESPE] ADD FOREIGN KEY ([ID_ESPECIALIDAD]) REFERENCES [dbo].[HER_ESPECIALIDAD] ([ID_ESPECIALIDAD]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

-- ----------------------------
-- Foreign Key structure for table [dbo].[HER_MEDICO]
-- ----------------------------
ALTER TABLE [dbo].[HER_MEDICO] ADD FOREIGN KEY ([ID_ESTADO_CIVIL]) REFERENCES [dbo].[HER_ESTADO_CIVIL] ([ID_ESTADO_CIVIL]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [dbo].[HER_MEDICO] ADD FOREIGN KEY ([ID_REGIONAL]) REFERENCES [dbo].[REGIONAL] ([ID_REGIONAL]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [dbo].[HER_MEDICO] ADD FOREIGN KEY ([ID_PERFIL_PROFESIONAL]) REFERENCES [dbo].[HER_PERFIL_PROFESIONAL] ([ID_PERFIL_PROFESIONAL]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [dbo].[HER_MEDICO] ADD FOREIGN KEY ([ID_PERFIL_PSICOGRAFICO]) REFERENCES [dbo].[HER_PERFIL_PSICOGRAFICO] ([ID_PERFIL_PSICOGRAFICO]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
ALTER TABLE [dbo].[HER_MEDICO] ADD FOREIGN KEY ([ID_PERFIL_PERSONAL]) REFERENCES [dbo].[HER_PERFIL_PERSONAL] ([ID_PERFIL_PERSONAL]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

-- ----------------------------
-- Foreign Key structure for table [dbo].[HER_PRODUCTO]
-- ----------------------------
ALTER TABLE [dbo].[HER_PRODUCTO] ADD FOREIGN KEY ([ID_LINEA]) REFERENCES [dbo].[HER_LINEA] ([ID_LINEA]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

-- ----------------------------
-- Foreign Key structure for table [dbo].[HER_SECRETARIA]
-- ----------------------------
ALTER TABLE [dbo].[HER_SECRETARIA] ADD FOREIGN KEY ([ID_LUGAR_TRABAJO]) REFERENCES [dbo].[HER_LUGAR_TRABAJO] ([ID_LUGAR_TRABAJO]) ON DELETE NO ACTION ON UPDATE NO ACTION
GO
